apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: autocontrol
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
  - name: jobType
    value: autocontrol
  - name: gatewayAddr
    value: localhost:265000
  - name: gatewayKeepAlive
    value: 45s
  - name: usePlainTextConnection
    value: true